---
project:
  islive: true
  name: {{ project_name }}
  root: /home/{{ project_name }}
  user: {{ project_name }}
  group: {{ project_name }}
  virtualenv: /home/{{ project_name }}/virtualenv
  settings: {{ project_name }}.conf.prod
  socket: /home/{{ project_name }}/run/uwsgi.sock
  pid: /home/{{ project_name }}/run/uwsgi.pid
  wsgi: {{ project_name }}.wsgi:application
  host: localhost
  proto: http

database:
  engine: postgresql_psycopg2
  name: {{ project_name }}
  user: {{ project_name }}
  host: "localhost"
  port: 5432
  {% verbatim %}password: "{{ lookup('password', '/tmp/database.password chars=ascii,numbers,digits length=15') }}"{% endverbatim %}

superuser:
  name: admin
  {% verbatim %}password: "{{ lookup('password', '/tmp/superuser.password chars=ascii,numbers,digits length=15') }}"{% endverbatim %}
  email: admin@example.com

search:
  active: true
  host: 127.0.0.1
  port: 9200
  index_name: {{ project_name }}

cms:
  active: true

bcrypt:
  active: true

compressor:
  active: true
