---
project:
  name: {{ project_name }}
  root: /home/{{ project_name }}
  user: {{ project_name }}
  group: {{ project_name }}
  virtualenv: /home/{{ project_name }}/virtualenv
  settings: {{ project_name }}.conf.vagrant
  socket: /home/{{ project_name }}/run/uwsgi.sock
  pid: /home/{{ project_name }}/run/uwsgi.pid
  wsgi: {{ project_name }}.wsgi:application
  requirements:
    - /vagrant/requirements.txt
    - /vagrant/requirements_prod.txt
