---
project:
  islive: false
  name: {{ project_name }}
  root: /vagrant
  user: vagrant
  group: vagrant
  virtualenv: /home/vagrant/virtualenv
  settings: {{ project_name }}.conf.vagrant
  socket: /home/{{ project_name }}/run/uwsgi.sock
  pid: /home/{{ project_name }}/run/uwsgi.pid
  wsgi: {{ project_name }}.wsgi:application
  host: localhost
  proto: http

database:
  engine: sqlite3
  name: database.db

superuser:
  name: admin
  password: admin
  email: admin@example.com

search:
  active: false
  host: 127.0.0.1
  port: 9200
  index_name: {{ project_name }}

cms:
  active: false

bcrypt:
  active: true
