---
- name: Configure django
  hosts: all
  sudo: yes
  roles:
    - { role: postgres }
    - { role: redis }
    - { role: django }
    - { role: uwsgi }
    - { role: nginx }
    - { role: elasticsearch }
    - { role: django-cms }
    - { role: django-compressor }
