{% verbatim %}
---
- name: Install required system packages.
  when: project.islive
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - nginx
  tags:
    - packages
    - provision
    - webserver
{% endverbatim %}
