{% verbatim %}
---
- name: remove default nginx site
  notify: restart nginx
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Install nginx configuration file.
  notify: restart nginx
  template: >
    src=vhost.conf.j2
    dest=/etc/nginx/sites-enabled/{{project.name}}
  tags:
    - configuration
    - nginx
    - webserver
    - update
{% endverbatim %}
