{% verbatim %}
---
- name: Create application group.
  when: project.islive
  group: name={{ project.group }} state=present

- name: Create application user and home.
  when: project.islive
  user: >
    home="{{ project.root }}"
    name="{{ project.user }}"
    group="{{ project.group }}"
    createhome=yes
    state=present
  tags:
    - base
    - user
    - provision
    - app

- name: Update sources in project root
  when: project.islive
  sudo: true
  copy: >
    src=../../../../../
    dest="{{ project.root }}/"
    owner="{{ project.user }}"
    group="{{ project.group }}"
    force=yes

- name: Change permissions
  when: project.islive
  sudo: true
  shell: "chown -R {{project.user}}:{{project.group}} {{project.root}}"
  tags:
    - base
    - user
    - provision
    - app
{% endverbatim %}
