{% verbatim %}
---
- name: Create Database Tables
  sudo_user: "{{project.user}}"
  django_manage: >
    command=syncdb
    app_path={{project.root}}
    settings={{project.settings}}
    virtualenv={{project.virtualenv}}
  tags:
    - database
    - app

- name: Migrate Django database.
  sudo_user: "{{project.user}}"
  django_manage: >
    command=migrate
    app_path={{project.root}}
    settings={{project.settings}}
    virtualenv={{project.virtualenv}}
  tags:
    - database
    - update
    - app
  notify:
    - restart uwsgi
{% endverbatim %}
