{% verbatim %}
---
- name: Install PIP Requirements.
  pip: >
    requirements={{item}}
    virtualenv={{project.virtualenv}}
  with_items: project.requirements
  tags:
    - packages
    - application
    - pip
    - app
{% endverbatim %}
