{% verbatim %}
---
- name: update base requirements
  sudo_user: "{{project.user}}"
  shell: "cat {{project.root}}/requirements/base/*.txt | xargs {{project.virtualenv}}/bin/pip install -U"

- name: update prod requirements
  when: project.islive
  sudo_user: "{{project.user}}"
  shell: "cat {{project.root}}/requirements/prod/*.txt | xargs {{project.virtualenv}}/bin/pip install -U"
{% endverbatim %}
