{% verbatim %}
---
- name: restart uwsgi
  sudo_user: root
  service: >
    name={{project.name}}-uwsgi
    state=restarted

- name: reload uwsgi
  sudo_user: root
  service: >
    name={{project.name}}-uwsgi
    state=restarted
{% endverbatim %}
