{% verbatim %}
---
- name: Create Database User
  when: database.engine == "postgresql_psycopg2"
  sudo: true
  sudo_user: postgres
  postgresql_user: >
    user='{{ database.user }}'
    password='{{ database.password }}'
    role_attr_flags=NOCREATEDB,NOSUPERUSER
    state=present
  tags: database

- name: Create Database.
  when: database.engine == "postgresql_psycopg2"
  sudo: true
  sudo_user: postgres
  postgresql_db: >
    name='{{ database.name }}'
    owner='{{ database.user }}'
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    state=present
  tags:
    - database
    - create
{% endverbatim %}
